name: Deploy

on:
  push:
    branches:
    - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}


  deployDocumentation:
    defaults:
      run:
        working-directory: documentation

    runs-on: ubuntu-latest
    steps:

      - name: Pull code
        uses: actions/checkout@v2


      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'


      - name: Install dependencies
        run: npm install


      - name: Build
        run: npm run build


      - name: Deploy
        if: success()
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "${{ secrets.FTP_SERVER }}"
          username: "${{ secrets.FTP_USERNAME_DOC }}"
          password: "${{ secrets.FTP_PASSWORD_DOC }}"
          local-dir: "documentation/build/"


  deployFrontend:
    runs-on: ubuntu-latest
    steps:

    - name: Pull code
      uses: actions/checkout@v2


    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'


    - name: Install dependencies
      run: npm install


    - name: Build
      run: npm run build:prod


    - name: Deploy
      if: success()
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: "${{ secrets.FTP_SERVER }}"
        username: "${{ secrets.FTP_USERNAME }}"
        password: "${{ secrets.FTP_PASSWORD }}"
        local-dir: "dist/"
